### ISSUE TITLE
Remove node_modules directory from version control

### ISSUE THREAD

**Issue by GrishMahat** [clienterrverse/clienterrverse_economy#2]
The repository currently includes the node_modules directory, which contains all the dependencies of the Node.js project. However, committing this directory to version control is not recommended for several reasons

Proposed Solution:

Remove the node_modules directory from version control.

Add a .gitignore file to exclude the node_modules directory and any other files or directories that shouldn't be committed

**Comment by cli3nterr** [comment]
Sure, thanks for letting me know that!

**Comment by GrishMahat** [comment]
@cli3nterr  can you check this I'm rewriting the whole code base https://github.com/GrishMahat/clienterrverse_economy
